#!/usr/bin/env node
// scripts/build.cjs

const { readFile, writeFile } = require('fs/promises');
const { resolve } = require('path');

// Define paths
const INPUT_FILE = resolve(__dirname, '../.browserslistrc');
const OUTPUT_CJS = resolve(__dirname, '../index.cjs');
const OUTPUT_MJS = resolve(__dirname, '../index.mjs');

(async () => {
  try {
    // Read and process .browserslistrc
    const raw = await readFile(INPUT_FILE, 'utf8');
    const entries = raw
      .split(/\r?\n/)
      .map((line) => line.replace(/\s*#.*$/, '').trim()) // Strip comments & trim
      .filter(Boolean); // Remove empty lines

    const jsonEntries = JSON.stringify(entries, null, 2);

    // Generate CommonJS module
    const cjsOutput = `// Autogenerated from .browserslistrc
module.exports = ${jsonEntries};
`;

    // Generate ES Module
    const mjsOutput = `// Autogenerated from .browserslistrc
export default ${jsonEntries};
`;

    // Write both files
    await Promise.all([
      writeFile(OUTPUT_CJS, cjsOutput, 'utf8'),
      writeFile(OUTPUT_MJS, mjsOutput, 'utf8'),
    ]);

    console.log(`✅ Generated index.cjs and index.mjs with ${entries.length} entries.`);
  } catch (error) {
    console.error('❌ Build failed:', error);
    process.exit(1);
  }
})();
