name: 📦 Update, Build & Publish (ESM)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-build-publish:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout code
      - uses: actions/checkout@v4

      # 2) Fetch latest .browserslistrc
      - name: Fetch Bootstrap .browserslistrc
        run: |
          curl -sL https://raw.githubusercontent.com/twbs/bootstrap/main/.browserslistrc \
            -o .browserslistrc.new
          mv .browserslistrc.new .browserslistrc

      # 3) Exit if unchanged
      - name: Check for changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet; then
            echo "No update → exiting"
            exit 0
          fi

      # 4) Build ESM module
      - name: Build index.cjs (ESM)
        run: npm run build

      # 5) Commit & bump
      - name: Commit & Tag
        run: |
          git add .browserslistrc index.cjs
          npm version patch --no-git-tag-version
          git commit -m "chore: update .browserslistrc → index.cjs ($(date +'%Y-%m-%d'))"
          git tag v$(node -p "require('./package.json').version")
          git push origin HEAD:main --follow-tags

      # 6) Publish
      - name: Setup Node.js & Publish
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
