name: 📦 Update, Build & Publish (ESM)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

concurrency:
  group: update-build-publish-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.diff.outputs.changed }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update .browserslistrc
        run: |
          curl -sL https://raw.githubusercontent.com/twbs/bootstrap/main/.browserslistrc \
            -o .browserslistrc

      - name: Check for changes
        id: diff
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

  build-and-publish:
    needs: check
    if: needs.check.outputs.changed == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Update .browserslistrc
        run: |
          curl -sL https://raw.githubusercontent.com/twbs/bootstrap/main/.browserslistrc \
            -o .browserslistrc

      - name: Build (ESM)
        run: npm run build

      - name: Bump version, commit & tag
        env:
          TZ: Europe/Berlin
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          npm version patch --no-git-tag-version
          git add .browserslistrc index.cjs package.json package-lock.json
          git commit -m "chore(release): v$(node -p "require('./package.json').version") [skip ci]"
          git tag v$(node -p "require('./package.json').version")
          git push origin HEAD:main --follow-tags

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
