name: 📦 Update, Build & Publish (ESM)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Bootstrap .browserslistrc
        run: |
          curl -sL https://raw.githubusercontent.com/twbs/bootstrap/main/.browserslistrc \
            -o .browserslistrc.new
          mv .browserslistrc.new .browserslistrc

      - name: Check for changes
        id: check
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

  update-build-publish:
    needs: check-for-changes
    if: needs.check-for-changes.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Bootstrap .browserslistrc
        run: |
          curl -sL https://raw.githubusercontent.com/twbs/bootstrap/main/.browserslistrc \
            -o .browserslistrc.new
          mv .browserslistrc.new .browserslistrc

      - name: Build index.cjs (ESM)
        run: npm run build

      - name: Commit & Tag
        run: |
          git add .browserslistrc index.cjs
          npm version patch --no-git-tag-version
          git commit -m "chore: update .browserslistrc → index.cjs ($(date +'%Y-%m-%d'))"
          git tag v$(node -p "require('./package.json').version")
          git push origin HEAD:main --follow-tags

      - name: Setup Node.js & Publish
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
